### ISSUE TITLE
Dimensions rendered incorrectly

### ISSUE THREAD

**Issue by ameennihad** [chilipeppr/widget-eagle#11]
Eagle lists dimension wires in the order the user draws them, however widget code assumes end of each wire matches the start of next one, and end of last wire matches the start of first one, which is true of most of the board but not all.
Following screenshot is taken from xpix workspace just to show that it's an old bug and not related to recent updates, it renders exactly the same with Version 5.1 of the widget (of course without the nice tabs that Frank Herrmann made)
![bug](https://cloud.githubusercontent.com/assets/24837471/21600697/8b81c320-d191-11e6-823b-3c01d125f5dd.png)

**Comment by chilipeppr** [comment]
What is generating those tabs for the dimensions? That's an awesome
feature. Was that something Frank added? Or did you add that?

**Comment by ameennihad** [comment]
Frank added that not me, really nice feature, can we pull from his repository? if not I can add his code with my next update.

**Comment by chilipeppr** [comment]
Hi Ameen, I just made you a collaborator on the Github project, so you
should be able to do more stuff as you see fit. Thanks for all of your
amazing help here. It's really great stuff. I'm already rethinking my
boards now that we can do double-sided. I'm excited about all the new
features and indeed these tabs would be awesome to have in the mix too.
This widget is getting really good.

**Comment by xpix** [comment]
Hello Friends, yes this change is needed for XDisPlace, first i cut the PCB and need this holder for further drill and mill. ok, i check my repository to find this changes and make a pull request.

**Comment by xpix** [comment]
PLease check this out:
https://github.com/chilipeppr/widget-eagle/pull/12

**Comment by chilipeppr** [comment]
BTW, both Frank and Ameen are now collaborators on Github for widget-eagle,
so feel free to do pull requests to the main branch, but I would like to
always check through them as well to catch anything that might look like it
could break something.

**Comment by chilipeppr** [comment]
Scanned through the code. Looks great and nothing worries me. Frank, do you
want to try to complete the pull request yourself then now that you are a
Collaborator?

**Comment by ameennihad** [comment]
I fixed board dimensions bug, please check my experimental workspace http://www.chilipeppr.com/ameen
Please try any weird shaped boards you might have.

**Comment by chilipeppr** [comment]
That's awesome. Even the Adafruit Ruler PCB has a dimension now. Prior to
your bug fix nothing was showing up for that. Wow, nice work again.
Incredible progress.

**Comment by ameennihad** [comment]
Code still needs some improvements, I just created a test board with complex dimensions, I see one wire went in the wrong direction, I'll check that tomorrow.

**Comment by chilipeppr** [comment]
How did you do it? Match up the x,y on each wire?

**Comment by ameennihad** [comment]
Yes, exactly.

**Comment by ameennihad** [comment]
I think I solved this bug for good, see before and after screenshots of the weirdest board I ever designed :), next steps is to handle cures in board dimensions.

**Before:**
![before](https://cloud.githubusercontent.com/assets/24837471/21635626/db735374-d26f-11e6-8618-d5725c984424.png)

**After:**
![after](https://cloud.githubusercontent.com/assets/24837471/21635657/f4349aee-d26f-11e6-9df1-1576897f7505.png)

**Comment by xpix** [comment]
Great News and welcome in our Team! :)

**Comment by chilipeppr** [comment]
Nice. That looks like you nailed it.
