### ISSUE TITLE
Generate Gcode with a comment on the line above the M6 tool change to help user jump to different sections when in Gcode widget

### ISSUE THREAD

**Issue by chilipeppr** [chilipeppr/widget-eagle#17]
![image](https://cloud.githubusercontent.com/assets/7904621/21725345/e8b37888-d3ec-11e6-821c-4ba6a745125b.png)

The Gcode widget generates a Tool Changes drop down. It looks at the M6 lines in the Gcode, and then the first comment above the M6 line becomes the label in this dropdown. It would be nicer to have the comment say the section name like "Drilling Vias" or "Milling Traces" as well as the tool diameter.

However, the Gcode widget will also look for Gcode comments of the format:
(T3 D=0.4 CR=0. - ZMIN=-0.5 - FLAT END MILL)

Where the tool number needs to be right after the open parentheses and then it regurgitates that comment in the pulldown menu like this example of Gcode from Fusion 360.

![image](https://cloud.githubusercontent.com/assets/7904621/21725488/85522004-d3ed-11e6-8f20-53c104d90675.png)

**Comment by ameennihad** [comment]
While I'm fixing the gcode bug I found lately, I decided to make the changes you mentioned here, please let me know if you have any notes. If there are no holes to mill, title of last tool change will only read **Milling Board Dimensions**.

I don't really know what is CR or ZMIN means!

![tool_change](https://cloud.githubusercontent.com/assets/24837471/21988169/62c5dbac-dc17-11e6-927f-594663598354.png)

**Comment by chilipeppr** [comment]
Oh, that looks awesome! This is really nice.

**Comment by ameennihad** [comment]
Implemented in V5.3
