### ISSUE TITLE
inchoate and inconsistent isolation of pins

### ISSUE THREAD

**Issue by jpadie** [chilipeppr/widget-eagle#23]
**use case:**
place standard pitch headers on a board and wire them up.  some should be of the same signal and some NC.  
example board here: https://dl.dropboxusercontent.com/u/194358/test.brd

**result:**
depending on the inflation amount, some identical headers are not isolated whereas others are.  this suggests an algorithm inaccuracy or perhaps that the algorithm is taking account of cream.
if one imagines that headers are being used as mechanical stability on a shield you would absolutely not want either the top or the bottom layers of the pins to be connected unless they were the same signal. 
see the following images:

![image](https://cloud.githubusercontent.com/assets/25035905/22852624/161fb808-f040-11e6-99fe-ce72c4766eb9.png)
(0.5 mm inflation - see the conflation of the same signal pins on both sides and the bloc-isolation of all the NC pins)

![image](https://cloud.githubusercontent.com/assets/25035905/22852631/42a3ffc4-f040-11e6-9591-29637c75f64d.png)

(0.2mm inflation - see that the pads are all correctly isolated).

**expected result:**
if a pin is capable of being isolated it should be isolated.  All pins should be isolated properly.  NC pins should be isolated instead of being treated as the same signal.  Importantly taking the example board, if the path inflation is put at 0.5mm (just about feasible for standard headers) then the unconnected pins will be isolated as if having the same signal.  however reduce the inflation to 0.15 and the pins are all properly isolated - which is correct.  

Yes - there is a workaround by giving each pin a signal - but then eagle complains.  and imagine a due or mega board - it doesn't make sense to name every signal when perhaps only 5 are going to be used on the shield.  

**Info/suggestions**
a signal that is 'undefined' should be treated as unique.

**Comment by ameennihad** [comment]
Thanks for reporting this issue, I believe the solution is simple, I'll try to fix this in V5.4.

**Comment by ameennihad** [comment]
Issue fixed, please test on my workspace

**Comment by chilipeppr** [comment]
Yeah, good call. A signal that is undefined should be unique. I did make
all undefined be treated as the same signal in v1 of this widget and your
analysis shows that it's better to make it unique.
