### ISSUE TITLE
Backlash issue or path calculation issue?

### ISSUE THREAD

**Issue by dgtlmoon** [chilipeppr/widget-eagle#30]
Hi all

Testing the importer using a fairly simple test BRD from EagleCad, I'm using a 60deg V-bit, with the _Inflate Milling Path By_ set to 0.55, the actual path sizing looks great, a couple of things I notice is that the drill positions are way off and theres definitely a problem with the cutting path, ignore the long line that intersects all 3 tests you can see on the big curves that it totally looses its position.

![screenshot_2017-02-17_11-04-26](https://cloud.githubusercontent.com/assets/275001/23063122/2d839e06-f509-11e6-9134-36f09f73f01b.png)

The final (top) PCB cutting i have flipped X and Y axis in the BRD importer to see what differences I'de see.

Each one has slightly different _"Inflate Milling Path By"_ settings, that seems to work wonderfully.

![20170217_115923](https://cloud.githubusercontent.com/assets/275001/23063221/ac1d7c14-f509-11e6-88f1-6720a77340b7.jpg)

And life would not be completed with the Chillipepr test..

![20170217_115945](https://cloud.githubusercontent.com/assets/275001/23063259/d6d9fc3e-f509-11e6-99b4-cffb36c0219c.jpg)

The technical specs for my CNC says "Backlash: approx. 0,08 mm / 0.003 inch(with software adjustable to 0,00 mm)" but obviously I've removed its controller and am using TinyG :)

Attached is my test BRD and GCode output

[mill-test.zip](https://github.com/chilipeppr/widget-eagle/files/783036/mill-test.zip)

Can anyone else reproduce this? Can someone perhaps try to cut that BRD file and reproduce the issue? (happy to buy pizza!)

**Comment by dgtlmoon** [comment]
Fixed, sorry guys - was a loose belt on the machine.

![20170217_143640](https://cloud.githubusercontent.com/assets/275001/23067283/ddbe87b2-f51e-11e6-88a4-7f3e7f769901.jpg)

**Comment by chilipeppr** [comment]
Nice work. That looks good although most folks don't mill as deep as you
did. I usually only mill down 0.1mm.

**Comment by dgtlmoon** [comment]
Thanks! actually I was nervous about what would happen when it was time to solder - how hard would it be to accidently solder across that gap given theres no solder mask... but turns out all was just fine, that small PCB was just a test piece, thanks for the great project!
