### ISSUE TITLE
Always attempts to drill registration holes, wont create gcode when disabled

### ISSUE THREAD

**Issue by dgtlmoon** [chilipeppr/widget-eagle#32]
In the gcode you can see the registration holes comment

![screenshot_2017-02-22_13-14-03](https://cloud.githubusercontent.com/assets/275001/23211201/2cbfb044-f901-11e6-8126-25d51defca42.png)

but..

![screenshot_2017-02-22_13-29-38](https://cloud.githubusercontent.com/assets/275001/23211565/0bebe4d0-f903-11e6-8730-13fe22fb4c24.png)

![screenshot_2017-02-22_13-33-20](https://cloud.githubusercontent.com/assets/275001/23211678/814366d6-f903-11e6-8700-43dbc3f65a91.png)

If I check `Blank FR4 Board` then uncheck the `Registration Holes` checkbox which is on by default, then uncheck `Blank FR4 Board`, then it gives me an error that I have no gcode to send..

![screenshot_2017-02-22_13-31-28](https://cloud.githubusercontent.com/assets/275001/23211609/400b23d4-f903-11e6-8ff3-1c0459f1c754.png)

**Comment by ameennihad** [comment]
Of course, because the gcode here is just for drilling the registration holes.
What gcode do you expect to see if you disable registration holes? The gcode for the board can be sent from the small icon on top right side of widget.

**Comment by dgtlmoon** [comment]
Ahuh ok, i didnt realise that this tab is ONLY activated when its open, as there are a few tabs that do combined functionality, closing, thanks

**Comment by chilipeppr** [comment]
I do think this layout/structure is getting confusing for folks. I had a
hard time trying to really understand that this Gcode was separate as well.
It's probably best to not put this "Blank FR4 Board" on the 1st tab because
it gives it too much prominence.

**Comment by dgtlmoon** [comment]
Yeah, it feels like I'm configuring  some parameter about the board I'm
using rather than a totally optional step
