### ISSUE TITLE
Roundness - SMD Pads

### ISSUE THREAD

**Issue by ameennihad** [chilipeppr/widget-eagle#37]
SMD pads are always rendered as rectangles because the roundness property is ignored.

![roundness](https://user-images.githubusercontent.com/24837471/28497741-9712ed9c-6f96-11e7-919d-d21b8d5196ee.jpg)

**Comment by ameennihad** [comment]
Roundness supported with V5.7

**Comment by chilipeppr** [comment]
Do you have an example file with round SMDs? I'd like to check it out. I
could use it as well for a screenshot and a Google+ post picture.

**Comment by ameennihad** [comment]
I don't have an example of a complete board, I just created one part for testing, I'm working on a board the we can use as an example, while testing the board I noticed a bug/limitation in the original code, SMD pads are always consider being on top layer unless the part is mirrored, in reality it's possible to have an SMD pad on bottom layer. I'll see if I can fix that.

**Comment by ameennihad** [comment]
Here is a sample file.
[ESP8266 Ring.zip](https://github.com/chilipeppr/widget-eagle/files/1595906/ESP8266.Ring.zip)

**Comment by chilipeppr** [comment]
Awesome. Thanks. This looks great.

[image: Inline image 1]
