### ISSUE TITLE
Bottom layer import from Eagle needs to be mirrored

### ISSUE THREAD

**Issue by momiccioli** [chilipeppr/widget-eagle#6]
When circuit designs are imported to CP from Eagle the bottom layer will be encoded as if it were the top layer.  Chilipeppr will need to create a mirror of the bottom layer before rendering and encoding to gcode.

A work around is to create a mirror of the bottom layer in eagle and then import it into Chilipeppr.  Chilipeppr will then render the board correctly as if it were the top layer.  There are videos that explain this on the Chilipeppr hangout.

**Comment by ameennihad** [comment]
This feature is now implemented in version 5.1 of the widget, I believe we should mark this issue as solved.

**Comment by momiccioli** [comment]
Excellent news I will test this in the next hour and confirm.

**Comment by momiccioli** [comment]
Confirmed this works!!!!!  Yahoo.
Had to include a picture of the end result.  Love the quality I get too.  This was accomplished using only a .6mm endmill and a single run!  Drills varied from .6mm up too 1.0mm.  Now if I only had a laser to etch out a solder mask!  Hmm.

![image](https://cloud.githubusercontent.com/assets/17304109/21624882/ec72d83c-d1d6-11e6-88c6-3a9493608230.png)
