### ISSUE TITLE
Include tabs in permiter mill of circuit boards

### ISSUE THREAD

**Issue by momiccioli** [chilipeppr/widget-eagle#7]
This is a feature request,  The ability to have tabs created as part of the perimeter mill of the board. These tabs will ensure the board stays in place during the final layers of the mill.  Otherwise the board could come loose and be damaged if it gets tangled up in the spindle.

**Comment by ameennihad** [comment]
Frank just pulled this feature from xpix workspace widget.

**Comment by chilipeppr** [comment]
The tabs look weird on the Arduino 2-layer board. And, the top cut on the
lower right seems to be gone. Hmm.
[image: Inline image 1]

Playing with the settings you can get something cleaner, but that last
segment seems lost of the top mill path in lower right corner of board in
screenshot.

[image: Inline image 2]

**Comment by ameennihad** [comment]
It seems that the screenshots were not uploaded!
I'm guessing that this is related to board dimensions bug, let's test after bug fix is pulled to main project.
